# Logs SIRETISATION

In [1]:
import glob, os, json
import pandas as pd
data = []
#os.chdir(r"data\logs\")
for file in glob.glob(r"data\logs\*.json"):
    with open(file) as f:
        for line in f:
            data.append(json.loads(line))

In [2]:
logs = pd.json_normalize(data)
logs

,key,total_to_siret_intial,total_stotal_siren_initialiren,total_to_siret_current,total_siren_current,total_match_rows_current,perc_total_match_rows_initial,total_match_siren_current,perc_total_match_siren_initial,perc_total_match_rows_current,perc_total_match_siren_current,check,df_no_duplication.nb_index,df_no_duplication.unique_siren,df_duplication.nb_index,df_duplication.unique_siren,df_duplication.df_not_duplicate_index.nb_index,df_duplication.df_not_duplicate_index.unique_siren,df_duplication.df_sp_index.nb_index,df_duplication.df_sp_index.unique_siren
0,0,7552898,4811139,7552898,4811139,4381198,0.580068,2928274,0.608645,0.580068,0.608645,3187871,4376190,2924688,11163,7958,5008,7958,6155,4688
1,1,7552898,4811139,3165545,2044055,143812,0.019041,102142,0.021230,0.045430,0.049970,3028718,142279,101032,5452,2211,1533,2211,3919,1261
2,2,7552898,4811139,3017814,1956016,435906,0.057714,325529,0.067662,0.144444,0.166425,2585673,434488,324413,2347,1821,1418,1821,929,783
3,3,7552898,4811139,2580979,1656872,94699,0.012538,70967,0.014751,0.036691,0.042832,2489419,93869,70225,2309,1567,830,1567,1479,882
4,4,7552898,4811139,2484801,1593351,169171,0.022398,153929,0.031994,0.068082,0.096607,2322103,166613,152005,3915,2799,2558,2799,1357,1010
5,5,7552898,4811139,2314273,1447362,121983,0.016150,86145,0.017905,0.052709,0.059519,2198063,119696,84149,3486,2598,2287,2598,1199,709
6,6,7552898,4811139,2191091,1371837,1745786,0.231141,1070848,0.222577,0.796766,0.780594,535758,1707435,1047666,52102,30341,38351,30341,13751,7987
7,7,7552898,4811139,431554,341458,50123,0.006636,32887,0.006836,0.116145,0.096313,383930,49044,32180,1420,943,1079,943,341,250

In [ ]:
logs[['total_match_rows_current']].sum()

In [ ]:
logs[['perc_total_match_rows_initial']].sum()

In [ ]:
logs[['perc_total_match_siren_initial']].sum()

In [ ]:
logs[['perc_total_match_rows_initial',
      'perc_total_match_siren_initial']].plot.bar(stacked=False)

In [ ]:
logs[['total_match_rows_current']].plot.bar(stacked=False)