# Test SageMaker

In [1]:
import boto3
import pandas as pd
from sagemaker import get_execution_role

#https://finditcalf.s3.eu-west-3.amazonaws.com/test/0101_1_20170512_112544_1_PM.csv
role = get_execution_role()
bucket='test'
data_key = '0101_1_20170512_112544_1_PM.csv'
data_location = 'https://finditcalf.s3.eu-west-3.amazonaws.com/{}/{}'.format(bucket, data_key)

data_location

'https://finditcalf.s3.eu-west-3.amazonaws.com/test/0101_1_20170512_112544_1_PM.csv'

In [2]:
pd.read_csv(data_location,sep=";")

,Code Greffe,Nom_Greffe,Numero_Gestion,Siren,Type_Inscription,Date_Immatriculation,Date_1re_Immatriculation,Date_Radiation,Date_Transfert,Sans_Activité,...,Type_Capital,Capital,Capital_Actuel,Devise,Date_Clôture,Date_Clôture_Except.,Economie_Sociale_Solidaire,Durée_PM,Date_Greffe,Libelle_Evt
0,101,Bourg-en-Bresse,2017B00696,829412410,P,2017-05-04,2017-05-04,NaN,NaN,NaN,...,F,2000.00,NaN,Euros,31 Décembre,2018-12-31,Non,99,2017-05-04,Création
1,101,Bourg-en-Bresse,2017B00709,829426089,P,2017-05-09,2017-05-09,NaN,NaN,NaN,...,F,1000.00,NaN,Euros,30 Septembre,2017-09-30,Non,99,2017-05-09,Création
2,101,Bourg-en-Bresse,2017B00703,829446152,P,2017-05-05,2017-05-05,NaN,NaN,NaN,...,F,100.00,NaN,Euros,31 Décembre,2017-12-31,Non,99,2017-05-05,Création
3,101,Bourg-en-Bresse,2017D00289,829421650,P,2017-05-04,2017-05-04,NaN,NaN,NaN,...,F,1200.00,NaN,Euros,NaN,NaN,Non,99,2017-05-04,Création
4,101,Bourg-en-Bresse,2017B00697,829413665,P,2017-05-04,2017-05-04,NaN,NaN,NaN,...,F,1500.00,NaN,Euros,31 Décembre,2017-12-31,Non,99,2017-05-04,Création
5,101,Bourg-en-Bresse,2017D00298,829484591,P,2017-05-09,2017-05-09,NaN,NaN,NaN,...,F,1000.00,NaN,Euros,NaN,NaN,Non,99,2017-05-09,Création
6,101,Bourg-en-Bresse,2017B00711,829489616,P,2017-05-09,2017-05-09,NaN,NaN,NaN,...,F,1000.00,NaN,Euros,30 Avril,2018-04-30,Non,99,2017-05-09,Création
7,101,Bourg-en-Bresse,2017B00700,829421031,P,2017-05-04,2017-05-04,NaN,NaN,NaN,...,F,3000.00,NaN,Euros,31 Décembre,NaN,Non,99,2017-05-04,Création
8,101,Bourg-en-Bresse,2017D00296,341180255,P,2017-05-09,1987-05-19,NaN,NaN,NaN,...,F,1527539.15,NaN,Euros,NaN,NaN,Non,50,2017-05-09,Création
9,101,Bourg-en-Bresse,2017D00295,829474774,P,2017-05-09,2017-05-09,NaN,NaN,Oui,...,F,2000.00,NaN,Euros,NaN,NaN,Non,99,2017-05-09,Création
10,101,Bourg-en-Bresse,2017B00704,829397611,P,2017-05-05,2017-05-05,NaN,NaN,Oui,...,F,1000.00,NaN,Euros,31 Décembre,2017-12-31,Non,99,2017-05-05,Création
11,101,Bourg-en-Bresse,2017D00300,829486117,P,2017-05-09,2017-05-09,NaN,NaN,NaN,...,F,300.00,NaN,Euros,NaN,NaN,Non,99,2017-05-09,Création
12,101,Bourg-en-Bresse,2017B00701,829423953,P,2017-05-04,2017-05-04,NaN,NaN,NaN,...,F,1000.00,NaN,Euros,31 Mai,2018-05-31,Non,99,2017-05-04,Création
13,101,Bourg-en-Bresse,2017B00710,829413517,P,2017-05-09,2017-05-09,NaN,NaN,NaN,...,F,5000.00,NaN,Euros,30 Juin,2018-06-30,Non,99,2017-05-09,Création
14,101,Bourg-en-Bresse,2017D00297,829479559,P,2017-05-09,2017-05-09,NaN,NaN,NaN,...,F,1000.00,NaN,Euros,NaN,NaN,Non,99,2017-05-09,Création
15,101,Bourg-en-Bresse,2017D00294,829450253,P,2017-05-05,2017-05-05,NaN,NaN,NaN,...,F,568000.00,NaN,Euros,NaN,NaN,Non,99,2017-05-05,Création